name: Compilation Projet C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v4

    - name: Compiler le programme principal
      # Utilisation de -Iinclude pour indiquer où se trouvent tes fichiers .h
      run: gcc -Iinclude src/*.c -o mypmap

    - name: Compiler les tests
      # src/main.c exclu pour éviter la double définition de main
      run: gcc -Iinclude tests/test_procfs.c src/procfs.c src/format.c src/options.c -o test_procfs